# Generated by Django 4.2.9 on 2024-01-20 07:07

import datetime
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today,
                        validators=[events.validators.must_future_date],
                        verbose_name="Дата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["title", "date"],
            },
        ),
    ]
