# Generated by Django 4.2.9 on 2024-01-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizations",
            field=models.ManyToManyField(
                related_name="events_organizations",
                to="organizations.organization",
                verbose_name="Организации",
            ),
        ),
    ]
