# Generated by Django 4.2.9 on 2024-01-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "postcode",
                    models.PositiveIntegerField(
                        verbose_name="Почтовый индекс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["title", "address"],
            },
        ),
    ]
